apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: tater-e2e
build:
  tagPolicy:
    dateTime:
      format: "local_20060102_150405"
      timezone: "Local"
  artifacts:
  - image: tater-api
    context: ./tater-api
    docker:
      dockerfile: ./environment/tater-api/Dockerfile
  - image: tater-db
    context: ./environment/tater-db
    docker:
      dockerfile: ./environment/tater-db/Dockerfile
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
    - name: tater-api
      chartPath: ./environment/tater-api/helm
      namespace: tater-e2e
      artifactOverrides:
        imageKey: tater-api
      imageStrategy:
        helm: {}
    - name: tater-db
      chartPath: ./environment/tater-db/helm
      namespace: tater-e2e
      artifactOverrides:
        imageKey: tater-db
      imageStrategy:
        helm: {}
    - name: wiremock
      repo: https://lebenitza.github.io/charts
      remoteChart: wiremock
      namespace: tater-e2e
      setValues:
        persistence:
          enabled: false
        serviceAccount:
          create: false
        service:
          port: 8080
          type: "NodePort"
portForward:
- resourceType: service
  resourceName: tater-api-svc
  namespace: tater-e2e
  port: 18000
  localPort: 18000
- resourceType: service
  resourceName: tater-db-svc
  namespace: tater-e2e
  port: 5432
  localPort: 18002
- resourceType: service
  resourceName: wiremock
  namespace: tater-e2e
  port: 8080
  localPort: 18001
profiles:
  - name: no-api
    patches:
      - op: remove
        path: /build/artifacts/0
      - op: remove
        path: /deploy/helm
      - op: remove
        path: /portForward/0