apiVersion: v1
metadata:
  name: tater-web-svc
kind: Service
spec:
  ports:
  - name: tater-web-svc
    protocol: TCP
    port: 18100
    targetPort: 80
  type: NodePort
  selector:
    name: tater-web