apiVersion: v1
metadata:
  name: tater-api-svc
kind: Service
spec:
  ports:
  - name: tater-api-svc
    protocol: TCP
    port: 18000
    targetPort: 8080
  type: NodePort
  selector:
    name: tater-api