apiVersion: apps/v1
kind: Deployment
metadata:
  name: tater-db
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: tater-db
  template:
    metadata:
      labels:
        name: tater-db
    spec:
      containers:
      - name: tater-db
        image: "{{.Values.imageKey.repository}}:{{.Values.imageKey.tag}}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "password"