apiVersion: apps/v1
kind: Deployment
metadata:
  name: tater-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: tater-api
  template:
    metadata:
      labels:
        name: tater-api
    spec:
      containers:
      - name: tater-api
        image: "{{.Values.imageKey.repository}}:{{.Values.imageKey.tag}}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: tater-secret
          mountPath: "/etc/tater"
          readOnly: true
      volumes:
      - name: tater-secret
        secret:
          secretName: tater-secret